### ISSUE TITLE
USER STORY: Delete post

### ISSUE THREAD

**Issue by mittnamnkenny** [mittnamnkenny/fishtales#10]
As a **Site User** I can **delete my own post** so that **I can interact with the content**

## Acceptance Criteria
- Registered and logged in users will be able to delete their own posts
- User should have to confirm before deleting their post

## Tasks
- [x] Create view code
- [x] Create html template or modal for delete post
- [x] Create link to access delete post
- [x] Connect urls
- [x] Test the completed functionality
