### ISSUE TITLE
USER STORY: Placeholder photos

### ISSUE THREAD

**Issue by mittnamnkenny** [mittnamnkenny/fishtales#13]
As a **Site User** the **placeholder photo when creating a post will be based on my fishing location if no photo is uploaded** so that **the blog will have more variation in photos**

## Acceptance Criteria
- Registered and logged in users will be able to create their own posts
- No uploaded photo when creating  a post will generate a placeholder photo based on chosen fishing location

## Tasks
- [x] Update default placeholder image with images matching the chosen fishing location
- [x] Create code to render matching placeholder image
- [x] Test the completed functionality
