### ISSUE TITLE
USER STORY: Fish caught

### ISSUE THREAD

**Issue by mittnamnkenny** [mittnamnkenny/fishtales#14]
As a **site user** I can **see the number of fish caught without entering the detail page for each post** so that **I can better select interesting posts**

## Acceptance Criteria
- Number of fish caught should be displayed on the list view for each post
- Should have a matching icon

## Tasks
- [x] Add Font Awesome fish icon to post in post list
- [x] Create code to show number of caught fish
- [x] Test the completed functionality
