### ISSUE TITLE
USER STORY: Weather info

### ISSUE THREAD

**Issue by mittnamnkenny** [mittnamnkenny/fishtales#15]
As a **site user** I can **see the weather conditions without entering the detail page for each post** so that **I can better select interesting posts**

## Acceptance Criteria
- Weather condition should be displayed on the list view for each post
- Should have matching icons

## Tasks
- [x] Add Font Awesome weather icons to post in post list
- [x] Create code to show the right icon based on weather conditions
- [x] Test the completed functionality
