### ISSUE TITLE
USER STORY: Number of comments

### ISSUE THREAD

**Issue by mittnamnkenny** [mittnamnkenny/fishtales#16]
As a **site user** I can **see the number of comments without entering the detail page for each post** so that **I can better select interesting posts**

## Acceptance Criteria
- Number of comments should be displayed on the list view for each post
- Should have a matching icon

## Tasks
- [x] Add Font Awesome comment icon to post in post list
- [x] Create code to show the number of comments
- [x] Test the completed functionality
