### ISSUE TITLE
USER STORY: Number of likes

### ISSUE THREAD

**Issue by mittnamnkenny** [mittnamnkenny/fishtales#17]
As a **site user** I can **see the number of likes without entering the detail page for each post** so that **I can better select interesting posts**

## Acceptance Criteria
- Number of likes should be displayed on the list view for each post
- Should have a matching icon

## Tasks
- [x] Add Font Awesome heart icon to post in post list
- [x] Create code to show the number of likes
- [x] Test the completed functionality
