### ISSUE TITLE
USER STORY: Account registration and login

### ISSUE THREAD

**Issue by mittnamnkenny** [mittnamnkenny/fishtales#2]
As a **Site User** I can **register an account** so that **I can share my fishing stories, comment and like**

## Acceptance Criteria
- To register a user must enter a username and password (email is optional)
- User should not be able to register the same username more than once

## Tasks
- [x] Install Allauth library
- [x] Create sign up / login links
- [x] Customize html templates
- [x] Test the completed functionality
