### ISSUE TITLE
USER STORY: View likes

### ISSUE THREAD

**Issue by mittnamnkenny** [mittnamnkenny/fishtales#21]
As a **Site User** I can **view the number of likes on each post** so that **I can see which is the most popular or viral**

## Acceptance Criteria
- Total number of likes should be visible when viewing a post
- Should include a matching icon

## Tasks
- [x] Create view code for likes
- [x] Update post detail template
- [x] Connect urls
- [x] Test the completed functionality
