### ISSUE TITLE
USER STORY: Like

### ISSUE THREAD

**Issue by mittnamnkenny** [mittnamnkenny/fishtales#22]
As a **Site User** I can **like a post** so that **I can interact with the content**

## Acceptance Criteria
- The user must be registered and logged in to like a post
- Should include a matching icon for toggle feature

## Tasks
- [x] Create view code for likes
- [x] Update post detail template
- [x] Connect urls
- [x] Test the completed functionality
