### ISSUE TITLE
USER STORY: Downvote

### ISSUE THREAD

**Issue by mittnamnkenny** [mittnamnkenny/fishtales#23]
As a **Site User** I can **downvote a post** so that **I can interact with the content**

## Acceptance Criteria
- The user must be registered and logged in to downvote a post
- Should include a matching icon for toggle feature

## Tasks
- [ ] Create view code for downvote
- [ ] Update post detail template
- [ ] Connect urls
- [ ] Test the completed functionality

**Comment by mittnamnkenny** [comment]
This user story will not be implemented. I do not think this contributes to an overall positive experience; the upvote functionality is enough for this purpose.
