### ISSUE TITLE
USER STORY: View comments

### ISSUE THREAD

**Issue by mittnamnkenny** [mittnamnkenny/fishtales#25]
As a **Site User** I can **view comments on an individual post** so that **I can read the conversation**

## Acceptance Criteria
- All comments should be visible when viewing a post
- Comments should be sorted by date created

## Tasks
- [x] Complete database model for comment
- [x] Create view code
- [x] Update html template for post list
- [x] Connect urls
- [x] Test the completed functionality
