### ISSUE TITLE
USER STORY: Comment on a post

### ISSUE THREAD

**Issue by mittnamnkenny** [mittnamnkenny/fishtales#26]
As a **Site User** I can **leave comments on a post** so that **I can be involved in the conversation**

## Acceptance Criteria
- Registered and logged in users will be able to leave comments on each post
- Name and date should be visible together with the comment

## Tasks
- [x] Create comment form with body field
- [x] Create view code
- [x] Update html template for post list
- [x] Create link to submit comment
- [x] Connect urls
- [x] Test the completed functionality
