### ISSUE TITLE
USER STORY: Delete Comment

### ISSUE THREAD

**Issue by mittnamnkenny** [mittnamnkenny/fishtales#27]
As a **Site User** I can **delete my own comment** so that **I can interact with the content**

## Acceptance Criteria
- Registered and logged in users will be able to delete their own comments
- User should have to confirm before deleting their comment

## Tasks
- [x] Create view code
- [x] Create html template or modal for delete comment
- [x] Create link to access delete comment
- [x] Connect urls
- [x] Test the completed functionality
