### ISSUE TITLE
USER STORY: Manage posts

### ISSUE THREAD

**Issue by mittnamnkenny** [mittnamnkenny/fishtales#3]
As a **Site Admin** I can **create, read, update and delete posts and comments** so that **I can manage my blog content**

## Acceptance Criteria
- Site admin can log in to the /admin URL with a superuser account
- Site admin can manage all posts with the included superuser account
- Site admin can manage all comments with the included superuser account

## Tasks
- [x] Complete database model for post and comment
- [x] Create superuser account
- [x] Build the Admin Site
- [x] Test the completed functionality
