### ISSUE TITLE
USER STORY: Responsive

### ISSUE THREAD

**Issue by mittnamnkenny** [mittnamnkenny/fishtales#30]
As a **Site User** I can **use the site on the following platforms: desktop, laptop, tablet and smartphone** so that **I can access all functionality**

## Acceptance Criteria
- Suitable graphics on different screen sizes
- User should be able to use the site successfully on small devices (320px wide)

## Tasks
- [x] Use media queries when needed
- [x] Collapse navigation bar on small devices
- [x] Test all pages using different screen sizes / platforms
