### ISSUE TITLE
USER STORY: Design

### ISSUE THREAD

**Issue by mittnamnkenny** [mittnamnkenny/fishtales#31]
As a **Site User** I can **get an overall positive impression based on the principles of user experience design, accessibility and responsivity** so that **I can quickly determine the purpose of the site and enjoy using it**

## Acceptance Criteria
- The user is presented with an easy to use navigation
- The site meets accessibility guidelines
- The user is presented with graphics that are consistent in style and colour

## Tasks
- [x] Create logo/brand in navigation bar
- [x] Create navigation items that are clearly labelled
- [x] Use custom font for headings
- [x] Use matching colour scheme on all pages
- [x] Design using accessibility guidelines
- [x] Test using Chrome DevTools Lighthouse
