### ISSUE TITLE
USER STORY: System messages

### ISSUE THREAD

**Issue by mittnamnkenny** [mittnamnkenny/fishtales#32]
As a **Site User** I will **get system messages when I interact with the site** so that **I get feedback when actions are completed**

## Acceptance Criteria
- Registered and logged in users will get feedback through pop-up messages
- The pop-up message should disappear automatically

## Tasks
- [x] Create code to display pop-up messages
- [x] Use JavaScript to make the message disappear after a set time
- [x] Test the completed functionality
