### ISSUE TITLE
USER STORY: Featurette

### ISSUE THREAD

**Issue by mittnamnkenny** [mittnamnkenny/fishtales#34]
As a **Site User** I am **presented with a featurette** so that **I can better understand the site’s purpose and features**

## Acceptance Criteria
- The user is presented with the featurette when visiting the front page
- Located below the hero image

## Tasks
- [x] Use at least 3 features
- [x] Include upscaled icons
- [x] Test using different screen sizes
