### ISSUE TITLE
USER STORY: Carousel

### ISSUE THREAD

**Issue by mittnamnkenny** [mittnamnkenny/fishtales#36]
As a **Site User** I can **view a carousel with new/recent posts** so that **I can easily see any post updates to the blog**

## Acceptance Criteria
- The user will be presented with an image slide-show
- The slide-show will update when a new post is added

## Tasks
- [x] Add Bootstrap carousel
- [x] Create code to display at least 3 images from recent blog posts
- [x] Test the completed functionality
