### ISSUE TITLE
USER STORY: GitHub link

### ISSUE THREAD

**Issue by mittnamnkenny** [mittnamnkenny/fishtales#37]
As a **Site User** I am **presented with a link to mittnamnkenny’s GitHub** so that ** I can view more repositories**

## Acceptance Criteria
- The link should be visible in the footer
- The link should include a Font Awesome icon

## Tasks
- [x] Complete footer section
- [x] Add Github link
- [x] Test that the link opens in new tab
