### ISSUE TITLE
USER STORY: View post list

### ISSUE THREAD

**Issue by mittnamnkenny** [mittnamnkenny/fishtales#6]
As a **Site User** I can **view a list of posts** so that **I can easily select one fishing story to read**

## Acceptance Criteria
- All posts are presented on the blog page
- Posts are sorted by date created
- Author, Image, title, and date created is shown on screen for each post
- Paginated view

## Tasks
- [x] Complete database model for post and comment
- [x] Create view code
- [x] Create html template for post list
- [x] Create link to access post list
- [x] Connect urls
- [x] Test the completed functionality
