### ISSUE TITLE
USER STORY: Open a post

### ISSUE THREAD

**Issue by mittnamnkenny** [mittnamnkenny/fishtales#7]
As a **Site User** I can **click on a post** so that **I can read the content**

## Acceptance Criteria
- Author, Image, title, date created, blog content, fish caught and location is available on screen
- Likes and comments are accessible

## Tasks
- [x] Complete database model for post and comment
- [x] Create view code
- [x] Create html template for post detail
- [x] Create link to access post detail
- [x] Connect urls
- [x] Test the completed functionality
