### ISSUE TITLE
USER STORY: Create post

### ISSUE THREAD

**Issue by mittnamnkenny** [mittnamnkenny/fishtales#8]
As a **Site User** I can **create my own posts** so that **I can share my fishing stories**

## Acceptance Criteria
- Registered and logged in users will be able to create their own posts
- User should complete the post form with the required fields
- User can upload their own photo

## Tasks
- [x] Create post form with required fields
- [x] Create view code
- [x] Create html template for add post
- [x] Create link to access add post
- [x] Connect urls
- [x] Test the completed functionality
