### ISSUE TITLE
USER STORY: Edit post

### ISSUE THREAD

**Issue by mittnamnkenny** [mittnamnkenny/fishtales#9]
As a **Site User** I can **edit my own post** so that **I can update the content**

## Acceptance Criteria
- Registered and logged in users will be able to edit their own posts
- User should complete the post form with the required fields

## Tasks
- [x] Create view code
- [x] Create html template for update post
- [x] Create link to access update post
- [x] Connect urls
- [x] Test the completed functionality
